llm:
  provider: openai
  model: gpt-4o-mini
  temperature: 0.7
  max_tokens: 10000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0

api:
  openai_api_key: 
  azure_formrecognizer_key: 
  azure_formrecognizer_endpoint:

chat:
  history_length: 10  # Number of previous messages to keep in context

chunking:
  chunk_size: 1000
  overlap: 200
  chunk_type: "RecursiveCharacterTextSplitter"
  supported_chunk_types:
    - RecursiveCharacterTextSplitter
    - TokenTextSplitter
    - CharacterTextSplitter
    - SemanticChunker
    - MarkdownHeaderTextSplitter

vector_store:
  persist_directory: ".chroma_db"  # Where to store vector DB files

exams_path: "./data/exams"  # Path to exams folder
force_reload: False