llm:
  provider: openai
  model: gpt-4o-mini
  temperature: 0.7
  max_tokens: 10000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0

api:
  openai_api_key: "INSERT-API-HERE"
  azure_formrecognizer_key: "INSERT-KEY-HERE"
  azure_formrecognizer_endpoint: "INSERT-ENDPOINT-HERE"

chat:
  history_length: 10  # Number of previous messages to keep in context

chunking:
  chunk_size: 1000 # 512
  overlap: 200     # 50
  chunk_type: "RecursiveCharacterTextSplitter"
  supported_chunk_types:
    - RecursiveCharacterTextSplitter
    - TokenTextSplitter
    - CharacterTextSplitter
    - SemanticChunker
    - MarkdownHeaderTextSplitter

vector_store:
  persist_directory: ".chroma_db"  # Where to store vector DB files

exams_path: "./api/exams_random"  # Path to exams folder
parsed_data_path: "./api/parsed_data.jsonl"
force_reload: False
